### ISSUE TITLE
로그아웃 기능을 잘 보이는데 위치시켰으면 함

### ISSUE THREAD

**Issue by yuyu154** [wbluke/miniprojects-2019#187]
로그아웃을 유저 수정 탭에서 한다는 것을 파악하기 힘들듯

**Comment by wbluke** [comment]
인스타가 그렇게 되어있어서 따라했습니당..ㅎㅎ

**Comment by yuyu154** [comment]
> 인스타가 그렇게 되어있어서 따라했습니당..ㅎㅎ

헐 그건 몰랐습니다
