### ISSUE TITLE
다른 유저의 게시물을 어떻게 볼 수 있는지 알기 어렵습니다.

### ISSUE THREAD

**Issue by kunggom** [wbluke/miniprojects-2019#193]
다른 유저를 팔로우하기 전까지는 인덱스 페이지에 아무 것도 보이지 않습니다. 또, 다른 유저의 존재 자체를 알기 어렵습니다.

**Comment by starkim06** [comment]
검색 기능이 안돼서 그런 것 같습니다. 곧 검색 기능 업데이트 하겠습니다.^^
