### ISSUE TITLE
다른 유저 페이지에 들어가기 위해 URI에 해당 유저 이름을 직접 입력해야 합니다.

### ISSUE THREAD

**Issue by kunggom** [wbluke/miniprojects-2019#194]
- URI에 유저 이름을 직접 입력해야 합니다.
- 유저 이름에 한글이 들어가면 URI에도 한글이 들어가게 됩니다.

**Comment by starkim06** [comment]
현재 검색 기능이 완성되지 않아서 그렇습니다. 수정하겠습니다.
