### ISSUE TITLE
포스팅의 시간이 절대 시간으로 나옵니다.

### ISSUE THREAD

**Issue by kunggom** [wbluke/miniprojects-2019#195]
절대 시간이란 `2019-08-30T07:46:19.55` 이런 형식을 뜻합니다. 가능하면 `3시간 전`과 같이 상대 시간으로 보여주거나, 혹은 `9월 5일`과 같이 뜨게끔 바꿔주면 좋겠습니다.

**Comment by starkim06** [comment]
추후 수정하도록 하겠습니다.
