### ISSUE TITLE
유저를 찾기가 어려웠어요. 어떻게 팔로우를 시작해야 할까요?

### ISSUE THREAD

**Issue by Deocksoo** [wbluke/miniprojects-2019#196]
처음 가입하고 팔로우하고싶은 사람의 페이지를 찾아들어가는 데에 어려움이 있었어요. 친구 이름으로 검색을 할 수 있게 하거나, 가입되어있는 유저 목록을 보여주면 어떨까요?

**Comment by wbluke** [comment]
검색 기능 만드는 중입니도 ㅎㅎ
