### ISSUE TITLE
다른 사람의 게시글 삭제했을 때 알림 메시지

### ISSUE THREAD

**Issue by Deocksoo** [wbluke/miniprojects-2019#207]
undefined가 뜨는데, 사유를 알 수 있으면 좋을것 같아요!

**Comment by starkim06** [comment]
아.....,. 사유가 궁금하게 만들어서 저희 서비스를 계속 이용하게 하는게 목적입니다.! 는 아니고 수정하겠습니다. 감사합니다 ㅎㅎ
