### ISSUE TITLE
로깅 정책

### ISSUE THREAD

**Issue by JunHoPark93** [wbluke/miniprojects-2019#48]
머지되고 나서, 다음 주에 역할 나눈뒤 이부분은 추가적으로 작업할게요. 한 분 같이 하면 좋을듯.
그리고 로그는 info 부터 쌓는게 어떨지. 디버그부터 쌓으면 생각보다 로그가 빨리차서 텍스트로만 서버용량 50gb는 후딱 채우더라구요.
그리고 error는 따로 zzazan _error.log 로 쌓아서 따로 관리하는게 좋을거같아요.
1~2일 단위로 배포해서, 집가는 도중이라도 수시로 앱 들어가서 막 터트리기 시도하고 다음 날 error log파일만 열어서 확인하면 버그도 빨리 잡을수 있을거같아요.

**Comment by wbluke** [comment]
와 넘모 멋지다ㅠㅠ
