### ISSUE TITLE
User 도메인 엔티티를 정합니다.

### ISSUE THREAD

**Issue by wbluke** [wbluke/miniprojects-2019#7]
- [ ] 아이디, 이름, 이메일, 비밀번호
- [ ] 팔로우하는 유저들
- [ ] 팔로잉하는 유저들

**Comment by starkim06** [comment]
도메인 제약사항
닉네임 : 2~10글자
이름 : 2~ 10글자
이메일 : 그냥 이메일
비밀번호 : 8글자 이상, 특수문자, 대문자 포함해서
프로필사진 주소 : null 가능, 유효한 url인지 검사 - head로 검사한다.
